version: '3'
services:
  template-multiple-dash:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: template-multiple-dash
    volumes:
      - ./logs:/app/logs:rw
    ports:
    - "5000:5000"
    networks:
      - default
      - nginx-net
    restart: unless-stopped
    command: /app/run_server.sh
    environment:
      VIRTUAL_HOST: template.ucsd.edu
      VIRTUAL_PORT: 5000
      LETSENCRYPT_HOST: template.ucsd.edu
      LETSENCRYPT_EMAIL: miw023@ucsd.edu
    deploy:
      resources:
        limits:
          memory: 8000M


networks:
  nginx-net:
    external:
      name: nginx-net