version: '3'
services:
  template-dash:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: template-dash
    volumes:
      - ./logs:/app/logs:rw
    ports:
    - "5000:5000"
    networks:
      - default
      - nginx-net
    restart: unless-stopped
    command: /app/run_server.sh
    environment:
      VIRTUAL_HOST: template.ucsd.edu
      VIRTUAL_PORT: 5000
      LETSENCRYPT_HOST: template.ucsd.edu
      LETSENCRYPT_EMAIL: miw023@ucsd.edu
    labels:
      - traefik.http.routers.gnpslcms-dash.rule=Host(`local.wanglab.science`) || Host(`local2.wanglab.science`)


networks:
  nginx-net:
    external:
      name: nginx-net